apiVersion: v1
kind: Pod
metadata:
  name: csi-test
  labels:
    app: csi-test
spec:
  containers:
    - name: csi-test
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /www
          name: csi-nfs
  restartPolicy: Always
  volumes:
    - name: csi-nfs
      persistentVolumeClaim:
        claimName: csi-pvc-test