# 将csi部署一下
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hello-csi
provisioner: hello.world.csi
parameters:
  server: "unix:///home/dong/project/csi-dev/csi.sock"
reclaimPolicy: Delete
volumeBindingMode: Immediate