apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
  labels:
    app: nfs-test-pod
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nfs
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh","-c","sleep 3600"]
      volumeMounts:
        - mountPath: /mnt
          name: nfs
  restartPolicy: Always
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: pvc


---
apiVersion: v1
kind: Service
metadata:
  name: nfs-test-pod
spec:
  selector:
    app: nfs-test-pod
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
  type: NodePort